### ISSUE TITLE
MakerBot package produces error — 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by homebysix** [autopkg/groob-recipes#2]
Both the MakerBot.download and MakerBot.munki recipes are failing at the moment.

```
$ autopkg run MakerBot.munki

Processing MakerBot.munki...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.groob-recipes/MakerBot/MakerBotURLProvider.py", line 57, in main
    self.env["url"] = self.get_makerbot_dmg_url(base_url)
  File "/Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.groob-recipes/MakerBot/MakerBotURLProvider.py", line 45, in get_makerbot_dmg_url
    url_bits = urlparse.urlsplit(m.group("filename"))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by groob** [comment]
Error was being caused by the regex filter not finding the url in the text. MakerBot changed the page I was scraping for the URL.
