### ISSUE TITLE
BoxEdit recipe erroring out with ValueError: NSInvalidArgumentException - data parameter is nil

### ISSUE THREAD

**Issue by childrss** [autopkg/groob-recipes#4]
Did my usual when recipes are failing:  nuked the autopkg/cache/pkgname/receipts, then nuked the cache/pkgname, then made sure the repo was up-to-date, then nuked and remade my override recipe (it only overrides where the download ends up in our munki repo).  

Nothing fixed it.

Let me know what I can do to help,

M@
# 

Processing BoxEdit.munki.recipe...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/**init**.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/**init**.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/Versioner.py", line 66, in main
    plist = FoundationPlist.readPlist(input_plist_path)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 116, in readPlist
    return _dataToPlist(data)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 74, in _dataToPlist
    data, NSPropertyListMutableContainersAndLeaves, None, None))
ValueError: NSInvalidArgumentException - data parameter is nil

**Comment by childrss** [comment]
Job started failing between 

```
Feb 6, 2015 1:34 PM  Jenkins reported failure
Feb 6, 2015 10:34 AM Jenkins reported last successful run
```
